# TODO: correctly handle
#version: '3.9'
services:
  actix-trust-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: actix-trust-service
    hostname: actix-trust-service
    container_name: actix-trust-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    # secrets:
    #   - 
    depends_on:
      - mongodb_container
      - ipfs
    environment:
      - RUNNING_IN_DOCKER=true
    profiles:
      - deploy
      
  mongodb_container:
    image: mongo:latest
    restart: unless-stopped
    hostname: mongo
    ports:
      - 27017:27017
    env_file: 
      - ./actix-server/.mongo.env
    volumes:
      - ./mongodb_data_container:/data/db
    profiles:
      - dev
      - deploy

  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs
    ports:
      #- "4001:4001"
      - "5001:5001"
      #- "8080:8080"
    volumes:
      - ipfs_data:/data/ipfs
    restart: unless-stopped
    profiles:
      - dev
      - deploy

volumes:
  mongodb_data_container:
  ipfs_data:
