# TODO: correctly handle 
version: '3.9'
services:
  actix-trust-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: actix-trust-service
    hostname: actix-trust-service
    container_name: actix-trust-service
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8081"
    # secrets:
    #   - 
    depends_on:
      - mongodb_container
    profiles:
      - deploy
  mongodb_container:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    env_file: 
      - .mongo.env
    volumes:
      - ./mongodb_data_container:/data/db
    profiles:
      - dev
      - deploy
volumes:
  mongodb_data_container:
