###
POST http://127.0.0.1:8081/api/dids

###
GET http://127.0.0.1:8081/api/dids/did:iota:lnk:0xe00971ab8ec13c0073c16cbabf565bc80e81485f1070ff2d1e8de7c3e99c08d9

###
POST http://127.0.0.1:8081/api/proofs
Content-Type: application/json

{
  "assetId": "id-asset-1",
  "assetHash": "ffffffffffffffffffffffffffffffffffffffffffff",
  "metadataHash": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
  "did": "did:iota:lnk:0xe00971ab8ec13c0073c16cbabf565bc80e81485f1070ff2d1e8de7c3e99c08d9"
}

###
GET http://127.0.0.1:8081/api/proofs?
    assetId=id-asset-1

###
GET http://127.0.0.1:8081/api/proofs/0x5698cac0766369fda5c8c393e1a50d04f3f1467f4d220edc663de688879549b80000

###
POST http://127.0.0.1:8081/api/nfts
Content-Type: application/json

{
  "assetId": "id-asset-1",
  "nftAlias": "ntf-asset-1",
  "nftSymbol": "AST-1",
  "license": "CC-BY-4.0",
  "did": "did:iota:lnk:0xe00971ab8ec13c0073c16cbabf565bc80e81485f1070ff2d1e8de7c3e99c08d9"
}

###
GET http://127.0.0.1:8081/api/nfts?
    assetId=id-asset-1

###
GET http://localhost:8081/api/log